import type { Category, MessageStyle } from './types';
import { generatedAvatarUri } from '@/constants/avatars';

export const NAMES = [
  'Kofi',
  'Kwame',
  'Ama',
  'Yaw',
  'Abena',
  'Kojo',
  'Akosua',
  'Fiifi',
  'Nana',
  'Kwesi',
  'Esi',
  'Adwoa',
  'Kweku',
  'Afia',
  'Mensah',
  'Owusu',
  'Asante',
  'Boateng',
  'Osei',
  'Serwaa',
  'Agyemang',
  'Charles',
  'Daniel',
  'Malik',
  'OTF',
  'Junior',
  'Paps',
  'Richie',
  'Kwabena',
  'Efua',
  'Yawson',
  'Addo',
  'Sarpong',
  'Aisha',
  'Ibrahim',
  'Blessing',
];

const POOLS: Record<Exclude<Category, 'statusRing'>, Record<Exclude<MessageStyle, 'mixed'>, string[]>> = {
  payment: {
    casual: [
      'Bro, how much should I send?',
      'Send me the payment details please.',
      'Bro I’m ready to pay, what’s the amount?',
      'What number should I send the money to?',
      'I’m about to pay now, drop the details.',
      'How much is left for me to send?',
      'Can I send it in two parts?',
      'Just tell me the amount and I’ll send it.',
      'Is MoMo okay or you want bank?',
      'I’ve got the money, where do I send it?',
      'Send the account before I forget.',
      'Should I add the charges on top?',
    ],
    friendly: [
      'Hey, I’m ready to settle this. What should I send?',
      'Can you share the payment details when you get a chance?',
      'I’ll pay now, just send me the number.',
      'What’s the total so I can send it over?',
      'Happy to pay today. Where should it go?',
      'Do you still want me to send the full amount?',
      'I can pay now if you drop the details.',
      'Let me know the amount and I’ll sort it.',
    ],
    professional: [
      'Please share the payment details at your earliest convenience.',
      'Kindly confirm the amount due so I can make payment.',
      'Could you send the account number for the transfer?',
      'I am ready to complete payment. Please advise the total.',
      'Please confirm whether Mobile Money or bank transfer is preferred.',
      'Kindly invoice the remaining balance so I can pay today.',
      'I will process payment once I receive the details.',
    ],
    ghana: [
      'Bro send the MoMo number make I pay.',
      'How much I go send now?',
      'I dey ready to pay, drop the details.',
      'Mtn or Vodafone, which one you dey use?',
      'Small time I go send am, how much be the last price?',
      'I get the money here, where I go send am?',
      'Make I send the full thing or I make am two times?',
      'Chale drop the number, I dey send am now.',
      'The charges too I go add or you go take am?',
      'I go pay this evening, send the account.',
    ],
  },
  price: {
    casual: [
      'How much is this one?',
      'Bro, what’s the price?',
      'Please send me the price.',
      'What’s the last price on this?',
      'Can you tell me how much?',
      'Is this still the same price?',
      'How much for two?',
      'What’s your best price?',
      'Just checking the price again.',
      'If I take it today, how much?',
    ],
    friendly: [
      'Hi, could you tell me the price for this?',
      'What’s the current price please?',
      'Would you mind sending the price again?',
      'How much would this come to?',
      'Is there a better price if I take it now?',
      'Can I get the price for the one we talked about?',
    ],
    professional: [
      'Please advise on the current price.',
      'Could you confirm the cost for this item?',
      'Kindly send a quotation when you can.',
      'What is the unit price, including delivery?',
      'Please confirm pricing so I can proceed.',
    ],
    ghana: [
      'How much be this one?',
      'Last price nti ɛyɛ sɛn?',
      'Chale the price nso ɛwɔ he?',
      'If I take two, how much I go pay?',
      'Reduce am small, how much be last?',
      'I want this one, how much?',
      'The other one how much, the small one.',
      'Price no still the same?',
    ],
  },
  appreciation: {
    casual: [
      'Bro, you’re really good. God bless you.',
      'Thanks bro, I really appreciate you.',
      'God bless you for this, bro.',
      'You really helped me, thank you.',
      'I appreciate this a lot.',
      'Big thanks, you came through.',
      'Respect. Thank you so much.',
      'You did well, I won’t forget this.',
      'Thanks for always being solid.',
      'I’m grateful, seriously.',
    ],
    friendly: [
      'Thank you so much, I really appreciate it.',
      'You’ve been so helpful, thank you.',
      'I’m really grateful for this.',
      'Thanks a lot, you made this easy.',
      'I appreciate you taking the time.',
      'God bless you, and thank you again.',
    ],
    professional: [
      'Thank you for your support. It is appreciated.',
      'I am grateful for your assistance.',
      'Thank you for handling this promptly.',
      'I appreciate your professionalism on this.',
      'Many thanks for your help.',
    ],
    ghana: [
      'Nyame nhyira wo, bro. Thank you.',
      'Chale you too good, God bless you.',
      'Medaase paa, I appreciate you.',
      'You tried, God bless you for this.',
      'Thank you bro, you dey always help.',
      'I no go forget this one. Thanks.',
      'God bless your hustle, thank you.',
      'You be real one. Medaase.',
    ],
  },
  general: {
    casual: [
      'You around?',
      'Let me know when you’re free.',
      'I’ll hit you back in a bit.',
      'Did you see my last message?',
      'We still on for later?',
      'Just checking in.',
      'Okay noted.',
      'Talk soon.',
      'You free this evening?',
      'Send me a message when you’re on.',
    ],
    friendly: [
      'Hey, hope you’re doing well.',
      'Just wanted to check in.',
      'Let me know when you’re free to talk.',
      'Hope your day is going okay.',
      'We can catch up later if that’s better.',
      'Ping me when you’re around.',
    ],
    professional: [
      'Please let me know a convenient time to talk.',
      'Following up on our last conversation.',
      'I am available this afternoon if needed.',
      'Kindly confirm when you are free.',
      'Noted, thank you. I will wait to hear from you.',
    ],
    ghana: [
      'Chale you dey?',
      'Make I know when you free.',
      'I go call you small time.',
      'You see the message I send?',
      'We still dey go ahead?',
      'I dey wait on you.',
      'Okay boss, I hear you.',
      'When you reach house, hit me.',
    ],
  },
  photo: {
    casual: [
      'Where we are 😄',
      'Look at this',
      'See the view',
      'This one 😂',
      'We’re here',
      'Check this out',
      'The food is ready',
      'Outside now',
    ],
    friendly: [
      'Thought you’d like this.',
      'Look where we ended up 😄',
      'Sending this from here.',
      'Beautiful spot today.',
      'Made me think of you.',
      'Here’s a quick snap.',
    ],
    professional: [
      'Please see the attached photo.',
      'Sharing the site photo as requested.',
      'Current status for your review.',
      'Photo of the item as discussed.',
    ],
    ghana: [
      'Where we dey 😄',
      'See the place',
      'Chale look this one',
      'We don reach oo',
      'Food dey ready',
      'I dey here, see',
    ],
  },
  voice: {
    casual: [''],
    friendly: [''],
    professional: [''],
    ghana: [''],
  },
  status: {
    casual: [
      'Yo man how far',
      'This one 🔥',
      'Where is this?',
      'You look good oo',
      'I saw this now',
      'Haha this one',
    ],
    friendly: [
      'Just saw your status 😄',
      'This looks great.',
      'Where was this taken?',
      'Nice one.',
      'You made my day with this.',
    ],
    professional: [
      'Nice update. Thank you for sharing.',
      'Looks good. Well done.',
      'Saw your latest post.',
    ],
    ghana: [
      'Yo man how far',
      'Chale this one 🔥',
      'Where you dey?',
      'You too much oo',
      'I see the status now',
      'E be you that?',
    ],
  },
};

export function messagesFor(category: Category, style: MessageStyle): string[] {
  const poolKey = category === 'statusRing' ? 'general' : category;
  if (style === 'mixed') {
    return (['casual', 'friendly', 'professional', 'ghana'] as const).flatMap(
      (key) => POOLS[poolKey][key]
    );
  }
  return POOLS[poolKey][style];
}

export function avatarUri(seed: string | number): string {
  return generatedAvatarUri(seed);
}
